version: '3.8'

services:
  jsonshop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: JsonShop
      SPRING_DATASOURCE_URL: jdbc:h2:mem:jsonshop
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.h2.Driver
      SPRING_DATASOURCE_USERNAME: jsonshop
      SPRING_DATASOURCE_PASSWORD: jsonshop
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.H2Dialect
      SPRING_H2_CONSOLE_ENABLED: 'true'
      SPRING_JPA_HIBERNATE_DDL_AUTO: update